blog/urls.py
from django.contrib import admin
from django.urls import path
from django.http import HttpResponse
from . import views


urlpatterns = [
    path('', views.post_list, name='post_list'),
    #path('(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
    path('<int:pk>/', views.post_detail, name='post_detail'),
    path('<int:post_pk>/comments/new/', views.comment_new, name='comment_new'),
    #path('<int:post_pk>/comments/(?P<pk>\d+)/edit/', views.comment_edit, name='comment_edit')
    path('<int:post_pk>/comments/<int:pk>/edit/', views.comment_edit, name='comment_edit'),
    path('<int:post_pk>/comments/<int:pk>/delete/', views.comment_delete, name='comment_delete')

]

hellomeltingpod/urls.py
from django.contrib import admin
from django.urls import path , include

from django.http import HttpResponse
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect


def hello(request):
    return redirect('blog:post_list')

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('blog/', include('blog.urls', namespace='blog')),
    path('blog/', include(('blog.urls', 'blog'), namespace ='blog')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', hello),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

from django.urls import reverse
from django.conf import settings

# Create your models here.
class Post(models.Model):
        title = models.CharField(max_length=100)
        content = models.TextField()
        photo = models.ImageField()
        created_at = models.DateTimeField(auto_now_add=True)
        updated_at = models.DateTimeField(auto_now=True)

        def _str_(self):
                return self.title

class Comment(models.Model):
        post = models.ForeignKey(Post, on_delete=models.PROTECT)  #20190613 added some code by jpanda 'on_delete'
        author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, db_constraint= False)
        message = models.TextField()

        def get_absolute_url(self):

                return reverse('blog:post_detail', args=[self.post_id])

blog/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
	class Meta:
		model =Comment
		#fields = '_all_'
		#fields = ('post','author','message',)
		fields = ('message',)

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView,DetailView,CreateView,UpdateView,DeleteView
from .models import Post
from .models import Comment
from .forms import CommentForm
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_list_or_404, get_object_or_404
from django.urls import reverse_lazy


# Create your views here.
'''
def post_list(request):
	return render(request, 'blog/post_list.html')

'''


post_list = ListView.as_view(model=Post)
post_detail = DetailView.as_view(model=Post)


class CommentCreateView(CreateView):
    model = Comment
    form_class = CommentForm
    template_name = 'blog/form.html'

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.post = get_object_or_404(Post, pk = self.kwargs['post_pk'])
        comment.author = self.request.user
        comment.save()
        return super(CommentCreateView, self).form_valid(form)

comment_new = login_required(CommentCreateView.as_view())

#comment_new = CreateView.as_view(model=Comment, form_class =CommentForm)

comment_edit = login_required(UpdateView.as_view(model=Comment, form_class = CommentForm, template_name='blog/form.html'))
comment_delete = login_required(DeleteView.as_view(model=Comment, success_url = reverse_lazy('blog:post_list')))

blog/templates/blog/base.html
<!doctype html>
<html>
<head>
<meta charset="utf8" />
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" />
<meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <link rel="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/flatly/bootstrap.min.css" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  
  <style>
	
  </style>
</head>

<body>

<nav class="navbar navbar-expand-sm bg-light">
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="#">Link 1</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Link 2</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Link 3</a>
    </li>
  </ul>
</nav>
<br>
{% block content%}
{% endblock%}

<hr/>
	{% if user.is_authenticated %}
		{{user}}
		<a href ="{% url "logout" %}?next=/"> LogOut</a>
	{%else%}
		<a href="{% url "login"%}">LogIn</a>
		
	{%endif%}


</body>
</html>

blog/templates/blog/comment_confirm_delete.html
{%extends "blog/base.html"%}

{%block content%}

<div class ="container">
	<div class ="row">
		<div class="col-sm-12">
			<div class="alert alert-danger">
				Do you really want to delete the comment?
			</div>
			<form action="" method="post">
				{% csrf_token %}
				<table>
					{{form.as_table}}
				</table>
				<input type="submit" class="btn btn-danger" />
			</form> 
		</div>
	</div>
</div>



{% endblock%}

blog/templates/blog/form.html
{%extends "blog/base.html"%}

{%block content%}

<div class ="container">
	<div class ="row">
		<div class="col-sm-12">

			<form action="" method="post">
				{% csrf_token %}
				<table>
					{{form.as_table}}
				</table>
				<input type="submit" />
			</form> 
		</div>
	</div>
</div>



{% endblock%}

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}

{% block content %}

<div class="container">
	<div class="row">
		<div class = "col-sm-12">
			<table class="table table-hover table-bordered">
				<h1> {{post.title}}</h1>
				<p><img src="{{post.photo.url}}" /></p>
				{{post.content|linebreaks}}
				<h4>Comment:</h4>
				<ul>
				{% for comment in post.comment_set.all %}
					<li>
						{{comment.message}}
						by {{comment.author}}
						<a href = "{%url "blog:comment_edit" post.pk comment.pk%}"> Modification</a>
					</li>
				{%endfor%}
				</ul>
				<hr/>
				<a href="{%url "blog:post_list" %}", class ="btn btn-primary"> To List </a>
				<a href="{%url "blog:comment_new" post.pk%}", class ="btn btn-primary"> Adding Comment </a>
			</table>
		</div>
	</div>
</div>



{%endblock%}

blog/templates/blog/post_list.html
{%extends "blog/base.html"%}

{%block content%}

<div class="container">
	<div class="row">
		<div class = "col-sm-12">
			<table class="table table-hover table-bordered">
				{% for post in post_list%}
					<tr>
						<td>
							<a href="{% url "blog:post_detail" post.pk %}">
								{{post.title}}
							</a>
						
						</td>
					</tr>
				{%endfor%}

			</table>
		</div>
	</div>
</div>
	




{% endblock%}